apiVersion: v1
kind: Service
metadata:
  name: {{ template "brigade-gcr-gateway.fullname" . }}
  labels:
    app: {{ template "brigade-gcr-gateway.name" . }}
    chart: {{ template "brigade-gcr-gateway.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  namespace: {{ .Values.brigade.namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: TCP
      name: http
  selector:
    app: {{ template "brigade-gcr-gateway.name" . }}
    release: {{ .Release.Name }}